platform :ios, '8.0'
use_frameworks!

target 'Paginator_Example' do
  pod 'Paginator', :path => '../'
  pod 'Paginator/ParametersProviders', :path => '../'

  target 'Paginator_Tests' do
    inherit! :search_paths

    pod 'OCMock'
  end
end
